version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  cypress: cypress-io/cypress@1.28.0
workflows:
  example-workflow:
    jobs:
      - heroku/deploy-via-git:
          force: true
          api-key: HEROKU_API_KEY
          app-name: $HEROKU_APP_NAME
          branch: main
      - cypress/run:
          start: npm start
