version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
parameters:
  api-key:
    default: 50abdacc-320e-4340-8dd3-8591982492f0
    description: The name of the environment variable containing your Heroku API Key.
    type: env_var_name